management:
#  server:
#    port: 9292
  endpoints:
    web: # ?? ?? ?? (web / jmx)
      exposure:
        include: "*"  # ??? ?? ( include / exclude)
  #        exclude: "env,beans"
#      base-path: "/manage" # ?? ?? ??
  endpoint:
    shutdown:
      enabled: true
    # ??
    health:
      show-components: always # ???(show-details), ???(show-components)
  # info
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
# info? env ?? ?? info... ?? ??
info:
  app:
    name: jiwon-actuator
    company: jw

# logging level ??
logging:
  level:
    hello.controller: debug

# metrics? tomcat ??? ?? ????? ?? ?? ???
server:
  tomcat:
    mbeanregistry:
      enabled: true